apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-complete-tool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-complete-tool
  template:
    metadata:
      labels:
        app: devops-complete-tool
    spec:
      containers:
        - name: devops-app
          image: irfannoorh.jfrog.io/docker-trial/complete-devops-app:latest
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: artifactory-registry-secret
