apiVersion: v1
kind: Service
metadata:
  name: devops-complete-service
spec:
  type: LoadBalancer
  selector:
    app: devops-complete-tool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
