pipeline{
    agent any

    environment{
        APP_NAME = "complete-devops-app"
        DOCKER_IMAGE = "${APP_NAME}:${BUILD_NUMBER}"

        ARTIFACTORY_SERVER= "irfannoorh.jfrog.io"
        ARTIFACTORY_USER = "maud0@eldver.com"
        ARTIFACTORY_REPO= "docker-trial"

        AWS_REGION = "ap-southeast-1"
        EKS_CLUSTER_NAME = "DevOps-Project"
    }

    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }

        stage('Build & Test'){
            steps{
                echo "Building Docker image: ${DOCKER_IMAGE}"
                sh "mvn clean package"
                echo "Build Completed Successfully"
            }
        }

        stage('SonarCloud Analysis'){
            steps{
                withSonarQubeEnv('SonarQube'){
                    sh "mvn sonar:sonar"
                }
            }
        }

        stage('Quality Gate'){
            steps{
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Docker Build & Push'){
            steps{
                script{
                    def fullImageName = "${ARTIFACTORY_SERVER}/${ARTIFACTORY_REPO}/${DOCKER_IMAGE}"
                    def latestImageName = "${ARTIFACTORY_SERVER}/${ARTIFACTORY_REPO}/${APP_NAME}:latest"

                    sh """
                        JFROG_TOKEN=\$(aws secretsmanager get-secret-value --secret-id devops/jfrog/token --region ${AWS_REGION} --query SecretString --output text | python3 -c "import json,sys; print(json.loads(sys.stdin.read())['JFROG_TOKEN'])")
                        echo "\$JFROG_TOKEN" | docker login -u "${ARTIFACTORY_USER}" --password-stdin "${ARTIFACTORY_SERVER}"
                        docker build -t ${fullImageName} -t ${latestImageName} .
                        docker push ${fullImageName}
                        docker push ${latestImageName}
                    """
                }
            }
        }

        stage('Deploy to EKS'){
            steps{
                script{
                    echo "Updating kubeconfig for cluster: ${EKS_CLUSTER_NAME} in ${AWS_REGION}"
                    sh "aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME} --region ${AWS_REGION}"

                    sh "kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml"

                    sh "kubectl rollout status deployment/devops-complete-tool --timeout=120s"
                }
            }
        }
    }

    post{
        success {
            echo "Pipeline Completed Successfully"
        }
        failure {
            echo "Pipeline Failed"
        }
    }
}